from tkinter import *
import pyautogui

root = Tk()
root.geometry("1300x420")
root.config(bg="black")
root.title("On-Screen Keyboard")
root.resizable(width=False, height=False)


def press():
    pass


class Buttons:
    def __init__(self, master, text, width=5, height=2, activebackground="grey30", activeforeground="black",
                 bg='grey20', fg="white", font="None 13", command=NONE):
        self.but = Button(master, text=text, width=width, height=height, bg=bg, fg=fg, font=font,
                          activebackground=activebackground, activeforeground=activeforeground, command=command,
                          borderwidth=0)
        self.but.bind("<Enter>", self.enter_col)
        self.but.bind("<Leave>", self.leave_col)

    def place(self, x, y):
        self.but.place(x=x, y=y)

    def config(self, **arg):
        self.but.config(arg)

    def enter_col(self, event):
        self.but.config(bg="floral white", fg="black")

    def leave_col(self, event):
        self.but.config(bg="grey20", fg="white")


# When shift is pressed
def shift_press():
    twiddle.config(text="~")
    one.config(text="!")
    two.config(text="@")
    three.config(text="#")
    four.config(text="$")
    five.config(text="%")
    six.config(text="^")
    seven.config(text="&")
    eight.config(text="*")
    nine.config(text="(")
    zero.config(text=")")
    minus.config(text="_")
    equal_to.config(text="+")
    sqr_bracket_left.config(text="{")
    sqr_bracket_right.config(text="}")
    backslash.config(text="|")
    semi_colon.config(text=":")
    single_quote.config(text='"')
    comma.config(text="<")
    full_stop.config(text=">")
    division.config(text="?")
    capitalize()


# When Caps_lock or shift is pressed
def capitalize():
    q.config(text="Q")
    w.config(text="W")
    e.config(text="E")
    r.config(text="R")
    t.config(text="T")
    y.config(text="Y")
    u.config(text="U")
    i.config(text="I")
    o.config(text="O")
    p.config(text="P")
    a.config(text="A")
    s.config(text="S")
    d.config(text="D")
    f.config(text="F")
    g.config(text="G")
    h.config(text="H")
    j.config(text="J")
    k.config(text="K")
    l.config(text="L")
    z.config(text="Z")
    x.config(text="X")
    c.config(text="C")
    v.config(text="V")
    b.config(text="B")
    n.config(text='N')
    m.config(text="M")


# TODO -> Row-1
esc = Buttons(root, text="Esc", width=4, height=1)
f1 = Buttons(root, text="F1", width=4, height=1)
f2 = Buttons(root, text="F2", width=4, height=1)
f3 = Buttons(root, text="F3", width=4, height=1)
f4 = Buttons(root, text="F4", width=4, height=1)
f5 = Buttons(root, text="F5", width=4, height=1)
f6 = Buttons(root, text="F6", width=4, height=1)
f7 = Buttons(root, text="F7", width=4, height=1)
f8 = Buttons(root, text="F8", width=4, height=1)
f9 = Buttons(root, text="F9", width=4, height=1)
f10 = Buttons(root, text="F10", width=4, height=1)
f11 = Buttons(root, text="F11", width=4, height=1)
f12 = Buttons(root, text="F12", width=4, height=1)
prtscr = Buttons(root, text="PrtScr", width=6, height=1)
insert = Buttons(root, text="Insert", width=6, height=1)

esc.place(x=0, y=0)
f1.place(x=67, y=0)
f2.place(x=134, y=0)
f3.place(x=201, y=0)
f4.place(x=268, y=0)
f5.place(x=335, y=0)
f6.place(x=402, y=0)
f7.place(x=469, y=0)
f8.place(x=536, y=0)
f9.place(x=603, y=0)
f10.place(x=670, y=0)
f11.place(x=737, y=0)
f12.place(x=804, y=0)
prtscr.place(x=871, y=0)
insert.place(x=965, y=0)

# TODO -> Row-2
twiddle = Buttons(root, text="`")
one = Buttons(root, text="1")
two = Buttons(root, text="2")
three = Buttons(root, text="3")
four = Buttons(root, text="4")
five = Buttons(root, text="5")
six = Buttons(root, text="6")
seven = Buttons(root, text="7")
eight = Buttons(root, text="8")
nine = Buttons(root, text="9")
zero = Buttons(root, text="0")
minus = Buttons(root, text="-")
equal_to = Buttons(root, text="=")
backspace = Buttons(root, text="Backspace", width=17, height=2)
page_up = Buttons(root, text="PgUp", width=5, height=2)

twiddle.place(x=0, y=73)
one.place(x=75, y=73)
two.place(x=150, y=73)
three.place(x=225, y=73)
four.place(x=300, y=73)
five.place(x=375, y=73)
six.place(x=450, y=73)
seven.place(x=525, y=73)
eight.place(x=600, y=73)
nine.place(x=675, y=73)
zero.place(x=750, y=73)
minus.place(x=825, y=73)
equal_to.place(x=900, y=73)
backspace.place(x=975, y=73)
page_up.place(x=1206, y=73)

# TODO -> Row-3
tab = Buttons(root, text="Tab", width=12, height=2, )
q = Buttons(root, text="q", )
w = Buttons(root, text="w")
e = Buttons(root, text="e")
r = Buttons(root, text="r")
t = Buttons(root, text="t")
y = Buttons(root, text="y")
u = Buttons(root, text="u")
i = Buttons(root, text="i")
o = Buttons(root, text="o")
p = Buttons(root, text="p")
sqr_bracket_left = Buttons(root, text="[")
sqr_bracket_right = Buttons(root, text="]")
backslash = Buttons(root, text="\\")
delete = Buttons(root, text="Del", width=10)
page_down = Buttons(root, text="PgDn")

tab.place(x=0, y=142)
q.place(x=166, y=142)
w.place(x=241, y=142)
e.place(x=316, y=142)
r.place(x=391, y=142)
t.place(x=466, y=142)
y.place(x=541, y=142)
u.place(x=616, y=142)
i.place(x=691, y=142)
o.place(x=766, y=142)
p.place(x=841, y=142)
sqr_bracket_left.place(x=916, y=142)
sqr_bracket_right.place(x=991, y=142)
backslash.place(x=1066, y=142)
delete.place(x=1141, y=142)

# TODO -> Row-4
caps_lock = Buttons(root, text="Caps ", width=12, height=2, command=capitalize)
a = Buttons(root, text="a")
s = Buttons(root, text="s")
d = Buttons(root, text="d")
f = Buttons(root, text="f")
g = Buttons(root, text="g", width=5, height=2)
h = Buttons(root, text="h")
j = Buttons(root, text="j")
k = Buttons(root, text="k")
l = Buttons(root, text="l")
semi_colon = Buttons(root, text=";")
single_quote = Buttons(root, text="'")
enter = Buttons(root, text="Enter", width=16, height=2, )
home = Buttons(root, text="Home")

caps_lock.place(x=0, y=211)
a.place(x=166, y=211)
s.place(x=241, y=211)
d.place(x=316, y=211)
f.place(x=391, y=211)
g.place(x=466, y=211)
h.place(x=541, y=211)
j.place(x=616, y=211)
k.place(x=691, y=211)
l.place(x=766, y=211)
semi_colon.place(x=841, y=211)
single_quote.place(x=916, y=211)
enter.place(x=991, y=211)
home.place(x=1206, y=211)

# TODO -> Row-5
lshift = Buttons(root, text="Shift", width=13, height=2, command=shift_press)
z = Buttons(root, text="z", )
x = Buttons(root, text="x")
c = Buttons(root, text="c")
v = Buttons(root, text="v")
b = Buttons(root, text="b")
n = Buttons(root, text="n")
m = Buttons(root, text="m")
full_stop = Buttons(root, text=".")
comma = Buttons(root, text=",")
division = Buttons(root, text="/")
rshift = Buttons(root, text="Shift", width=15, height=2)
end = Buttons(root, text="End")

lshift.place(x=0, y=280)
z.place(x=179, y=280)
x.place(x=254, y=280)
c.place(x=329, y=280)
v.place(x=404, y=280)
b.place(x=479, y=280)
n.place(x=554, y=280)
m.place(x=629, y=280)
comma.place(x=704, y=280)
full_stop.place(x=779, y=280)
division.place(x=854, y=280)
rshift.place(x=1004, y=280)
end.place(x=1206, y=280)

# TODO -> Row-6
lctrl = Buttons(root, text="Ctrl", )
fn_key = Buttons(root, text="Fn", )
win_key = Buttons(root, text="Win")
l_alt = Buttons(root, text="Alt")
space = Buttons(root, text="Space", width=36, height=2)
r_alt = Buttons(root, text="Alt")
rctrl = Buttons(root, text="Ctrl")
left_arrow = Buttons(root, text="\u2190")
up_arrow = Buttons(root, text="\u2191")
down_arrow = Buttons(root, text="\u2193")
right_arrow = Buttons(root, text="\u2192")

lctrl.place(x=0, y=349)
fn_key.place(x=75, y=349)
win_key.place(x=150, y=349)
l_alt.place(x=225, y=349)
space.place(x=300, y=349)
r_alt.place(x=779, y=349)
rctrl.place(x=1079, y=349)
up_arrow.place(x=929, y=280)
left_arrow.place(x=854, y=349)
down_arrow.place(x=929, y=349)
right_arrow.place(x=1004, y=349)

root.mainloop()
